### ISSUE TITLE
Don't import all languages

### ISSUE THREAD

**Issue by metachris** [metachris/vue-highlightjs#10]
> If we use vue-highlightjs with webpack, we get a huge bundle size, due to all the useless languages that imported by default in highlight.js's entry highlight.js/lib/index.js.

See #9

**Comment by mickdekkers** [comment]
I'll give this a shot if no one else is currently working on it :)

**Comment by mrodal** [comment]
Any progress with this? It would be really useful

**Comment by satel008** [comment]
How to buddle those languages I used only with webpack? Is there any relevant doc?

**Comment by phuze** [comment]
[highlight.js](https://github.com/highlightjs/highlight.js) now supports vue through its own [vue plugin](https://github.com/highlightjs/vue-plugin).

```
npm i highlight.js @highlightjs/vue-plugin
```

The plugin supports importing only languages you need.

```js
// highlight.js
import hljs from 'highlight.js/lib/core';
import json from 'highlight.js/lib/languages/json';
import vuePlugin from "@highlightjs/vue-plugin";
hljs.registerLanguage('json', json);
Vue.use(vuePlugin);
```

**Comment by metachris** [comment]
Thanks for the heads-up! I will update the README and point to the official implementation 👍

**Comment by metachris** [comment]
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3
