### ISSUE TITLE
<textarea v-highligthjs><code class="java"></code></textarea>??

### ISSUE THREAD

**Issue by vela-security** [metachris/vue-highlightjs#12]
???

**Comment by metachris** [comment]
I don't understand what you mean with this issue. Have you encountered a problem?

**Comment by vela-security** [comment]
I want to highlight the code in the textarea ？

**Comment by vela-security** [comment]
But the official seems to support only the <pre><code>, which can be changed to <textarea v-highligthjs><code class="java"></code></textarea> ? What should I do?

**Comment by metachris** [comment]
Not sure how that works, but this is the wrong repo for that question. You should try to figure it out with plain JS + HighlightJS first: https://highlightjs.org/

Once that works for you, you can open another ticket and post your code, then we'll take a look from there.

**Comment by ajthinking** [comment]
Im also interested in this. Found a [JSfiddle](https://codepen.io/Macavity/pen/KQNWdg). It seems to work as long as I dont scroll with mouse, that will make the cursor go crazy.
