### ISSUE TITLE
[Vue warn]: Failed to resolve directive: hightlightjs

### ISSUE THREAD

**Issue by tomas-nielsen** [metachris/vue-highlightjs#14]
When I'm trying to use the npm package i get

`[Vue warn]: Failed to resolve directive: hightlightjs`

i my `index.js` I have:
```
import VueHighlightJS from 'vue-highlightjs'
Vue.use(VueHighlightJS) 
```
Vue is already imported in another js file, loaded before this
in my component:
```
<pre v-hightlightjs="code">
        <div v-if="desc" class="codeDesc">{{desc}}</div>
        <code :class="type"></code>
</pre>
```
where code and type are props

What am I doing wrong?

**Comment by sejr** [comment]
I am experiencing this issue as well.

**Comment by Narven** [comment]
@tomas-nielsen did you found the reason? thanks

**Comment by igorkosta** [comment]
Has anyone found out what's causing the problem?

**Comment by bharatkashyap** [comment]
I think you might be spelling the directive wrong: It should be **v-highlight** and not **v-hightlight**.

**Comment by tomjrjones** [comment]
Did anybody find a workaround, I'm having the same issue?

**Comment by bardaxx** [comment]
Same problem here

**Comment by AlexZhong22c** [comment]
you guys may install a wrong npm package as a mistake.

checkout this npm package out https://github.com/gluons/vue-highlight.js, it's name is very similar to this one.

i just install by `yarn add vue-highlight.js`, and fall to that one.

**Comment by AlexZhong22c** [comment]
please console.log the value of `VueHighlightJS` to see the module name. this 2 package share the same usage. and the stupid tutorials of Internet mislead me, they totally mix them up.

**Comment by guapi233** [comment]
AlexZhong22c is right !

**Comment by metachris** [comment]
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3
