### ISSUE TITLE
Allow highlightjs options to be passed in

### ISSUE THREAD

**Issue by ericcirone** [metachris/vue-highlightjs#15]
Would love to be able to pass in highlightjs options when initializing vue-highlightjs

**Comment by ericcirone** [comment]
#16 solves this issue

**Comment by simonerlandsen** [comment]
@metachris should this PR be merged?

**Comment by metachris** [comment]
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3
