### ISSUE TITLE
No styles/stylesheets present

### ISSUE THREAD

**Issue by Octavector** [metachris/vue-highlightjs#19]
Following the process outlined:

**Installed vue-highlightjs:**
```
npm install --save vue-highlightjs
```
**Imported in `main.js`:**

```js
import Vue from 'vue'
import VueHighlightJS from 'vue-highlightjs'
Vue.use(VueHighlightJS)
```

**Used in component callled by vue-router:**
```html
<pre v-highlightjs><code class="javascript">const s = new Date().toString()</code></pre>
```

My output is without styling. vue-highlightjs appears to be doing its job as the output has the correct class names:

```html
<pre>
   <code class="javascript hljs">
      <span class="hljs-keyword">const</span> s = <span class="hljs-keyword">new</span> <span class="hljs-built_in">Date</span>().toString()
   </code>
</pre>
```

What method do I use to apply the styles? Should they have been added automatically or do I need to add them in the component or add them with Webpack?

**Comment by ghost** [comment]
### highlight.js
```javascript
npm install --save highlight.js
```
### Styles

```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/styles/default.min.css">
```

### Source

[https://www.metachris.com/2017/02/vuejs-syntax-highlighting-with-highlightjs/](https://www.metachris.com/2017/02/vuejs-syntax-highlighting-with-highlightjs/)

**Comment by Octavector** [comment]
@vegenera Thank you!
