### ISSUE TITLE
Import CSS helper

### ISSUE THREAD

**Issue by mix3d** [metachris/vue-highlightjs#21]
This package does not seem to automatically include the highlightjs CSS file, nor do the docs mention the need to manually do so. (Assumed all styles would be included with the vue-package).

Am I missing something, or is there a need to modify docs a little? Maybe update to manually include the CSS from the highlightjs npm package?

**Comment by adamdahan** [comment]
yah like dah? had the same problem now too.

**Comment by VictorWinberg** [comment]
You can write `import "highlight.js/styles/github.css";` in your vue `main.js` file to import the style you want.

**Comment by satel008** [comment]
I encountered the same problem with you, and I tried to do as follows,
```
<style>
    @import '../../style/highlightjs.css';
</style>
```
yet it didn't  work.

**Comment by govarthananve** [comment]
Please install

> npm i highlight.js or yarn add highlight.js

Now import that css file into main.js 

> import 'highlight.js/styles/default.css';

**Comment by metachris** [comment]
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3
