### ISSUE TITLE
Vuetify overwrites this...

### ISSUE THREAD

**Issue by SumNeuron** [metachris/vue-highlightjs#25]
Tried using with Vuetify. Sadly to no avail. :/

**Comment by mgramin** [comment]
Same on vuetify 2.0.18

**Comment by BotellaA** [comment]
any workaround?

**Comment by KryptoBeard** [comment]
I also cannot get this work work with Vuetify at all. Everything is overridden.

**Comment by Hexodus** [comment]
I wrote about Vuetify+HighlightJS usage on [Stackoverflow](https://stackoverflow.com/a/63796949/1600193) though without this plugin but it might still be useful to some of you.

**Comment by metachris** [comment]
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3
