### ISSUE TITLE
incompatible with v-pre, how to make it work with curly brackets ?

### ISSUE THREAD

**Issue by vesper8** [metachris/vue-highlightjs#26]
I want to print and highlight the following code

```
{{ number + 1 }}
{{ ok ? 'YES' : 'NO' }}
{{ message.split('').reverse().join('') }}
<div v-bind:id="'list-' + id"></div>
```

I tried with this

```
      <pre
        v-pre
        v-highlightjs
        class="code"
      ><code class="lang-html">
{{ number + 1 }}
{{ ok ? 'YES' : 'NO' }}
{{ message.split('').reverse().join('') }}
<div v-bind:id="'list-' + id"></div>
</code></pre>
```

If I add the `v-pre` it prints but removes all highlighting
If I leave the v-pre out, it of course throw a JS error saying that number, ok and message are not defined.

I'm unsure why v-pre cancels out v-highlightjs.. anyone know how I can get highlighting AND include curly brackets inside my "demonstration" code snippet?

**Comment by vesper8** [comment]
I managed to get around by wrapping my curly brackets like so:

`{{ msg }}` -> `<template v-pre>{{ msg }}</template>`

**Comment by metachris** [comment]
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3
