### ISSUE TITLE
if data is null, can't show right content

### ISSUE THREAD

**Issue by xmut** [metachris/vue-highlightjs#28]
<pre v-highlightjs="sourcecode"><code class="javascript"></code></pre>

if sourcecode is null, then highlightjs can't change content.
for example:
Step 1. sourcecode=null, show empty string;   OK
Step 2. sourcecode='abc', show: abc;  OK
Step 3. sourcecode=null, still show: abc; NG

i slove it:
sourcecode === null ? '' : sourcecode

**Comment by metachris** [comment]
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3
