### ISSUE TITLE
Newline between <pre> and <code>

### ISSUE THREAD

**Issue by soichih** [metachris/vue-highlightjs#5]
I am having trouble getting rid of unnecessary white space before and after the highlightjs content. 

Here is the exact HTML content generated by vue2

```
<pre data-v-4ae6567b="" style="background-color:  red;margin: 0px;">
                <code data-v-4ae6567b="" class="basic hljs">seems <span class="hljs-keyword">to</span> be running <span class="hljs-keyword">on</span> karst
</code>
            </pre>
```

As you can see, there are newlines before and after `<code></code>` section, and browser is rendering empty lines because it's inside `<pre>` tag. How can I get rid of this?

**Comment by metachris** [comment]
Hi! I'll look into it. Can you please also post the Vue template / a full
working example? Thanks!

**Comment by soichih** [comment]
@metachris 

Sorry, I was trying to create the working test case, and it turned out that it was my own template that was adding the space.. duh!

I am closing this issue.

**Comment by metachris** [comment]
No problemo! Glad it works now ;)
