### ISSUE TITLE
Add default style in README.md

### ISSUE THREAD

**Issue by gengjiawen** [metachris/vue-highlightjs#8]
Maybe add the default style to REAME.md will be more clear. Something like this:
```js
import 'highlight.js/styles/default.css'
```

**Comment by chrisroselli** [comment]
Ya. took me about an hour to figure this out, ha.

**Comment by SumNeuron** [comment]
how to change style?

**Comment by j6k4m8** [comment]
@SumNeuron check out the list of .css files in that directory under `node_modules`. Replace with a different filename to get a different style.

**Comment by metachris** [comment]
Closing this issue because this project is officially superseded by https://github.com/highlightjs/vue-plugin

Thanks for participating <3
